name: smos-convert-org
version: 0.1.2
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - attoparsec
  - base
  - bytestring
  - containers
  - mtl
  - optparse-applicative
  - orgmode-parse
  - path
  - path-io
  - smos-data
  - text
  - time
  - unordered-containers
  - validity

executables:
  smos-convert-org:
    main: Main.hs
    source-dirs: app
    dependencies:
    - base
    - smos-convert-org
