name: smos-api
version: 0.3.1
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2019-2021 Tom Sydney Kerckhove'
license: MIT
homepage: https://github.com/NorfairKing/smos

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - aeson
  - autodocodec
  - autodocodec
  - base64-bytestring
  - bytestring
  - cryptonite
  - deepseq
  - dirforest
  - hashable
  - http-api-data
  - memory
  - mergeful
  - mergeful-persistent
  - password
  - password-instances
  - path
  - path-pieces
  - persistent
  - semver
  - servant
  - servant-auth
  - servant-auth-server
  - smos-data
  - smos-report
  - text
  - time
  - typed-uuid
  - uuid
  - validity
  - validity-bytestring
  - validity-path
  - validity-text
  - validity-uuid
