name: smos-server
version: 0.5.0
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  build-tools: autoexporter
  dependencies:
  - aeson
  - aeson-pretty
  - autodocodec
  - autodocodec-yaml
  - bytestring
  - conduit
  - containers
  - dirforest
  - envparse
  - filepath
  - http-client
  - jose
  - looper
  - mergeful
  - microlens
  - monad-logger
  - mtl
  - optparse-applicative
  - path
  - path-io
  - persistent
  - persistent-sqlite
  - persistent-template
  - pretty-show
  - semver
  - servant
  - servant-auth-server
  - servant-server
  - smos-api
  - smos-data
  - smos-report
  - stripe-client
  - template-haskell
  - text
  - time
  - typed-uuid
  - unliftio
  - unordered-containers
  - wai
  - wai-extra
  - warp
  - yaml
  - zip
  - zstd

executables:
  smos-server:
    main: Main.hs
    source-dirs: app
    dependencies:
    - smos-server
