name: smos-github
version: 0.4.1
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
license: MIT

extra-source-files:
  - test_resources/**/*

library:
  source-dirs: src/
  ghc-options: -Wall
  build-tools: autoexporter
  dependencies:
    - aeson
    - async
    - autodocodec
    - base
    - conduit
    - containers
    - envparse
    - github
    - network-uri
    - optparse-applicative
    - path
    - path-io
    - safe-coloured-text-terminfo
    - smos-data
    - smos-query
    - smos-report
    - text
    - time
    - validity
    - validity-path
    - validity-text

executables:
  smos-github:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - base
    - smos-github

tests:
  smos-data-test:
    main: Spec.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - base
    - genvalidity
    - genvalidity-sydtest
    - genvalidity-text
    - genvalidity-time
    - github
    - path
    - smos-data-gen
    - smos-github
    - sydtest
    - time
